version: "3.8"

services:
  db:
    image: imrahulmohanan/contactsapp:db-latest
    container_name: mysql-contact-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: contact_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  api:
    image: imrahulmohanan/contactsapp:api-latest
    container_name: contact-api
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/contact_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysqlpassword
    ports:
      - "9090:9090"

  ui:
    image: yourdockerhubuser/contact-app:ui-latest
    container_name: contact-ui
    restart: always
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:9090/api/contacts
    ports:
      - "3000:3000"

volumes:
  db-data:
